### PR TITLE
fix issue #17

### PR DESCRIPTION
**Pull request by fangjianmin**
fix the issue #17
the wrong mailinglist href.
three errors.
[issue #17 ](issue #17 )

### CODE REVIEW

**Comment by fangjianmin** [comment]
@xuechaos 
pls verified that.

**Comment by xuechaos** [comment]
@fangjianmin good, but delete '+subscribe' have a problem.
```
Send an email to (Group Name)+subscribe@googlegroups.com. +subscribe is the key, which is appended to the end of group’s email address. (Group Name) is the name of the group. Space is substituted by “-” (hyphen).
```
could you fix it ? thank you.

**Comment by fangjianmin** [comment]
> @fangjianmin good, but delete '+subscribe' have a problem.
> 
> ```
> Send an email to (Group Name)+subscribe@googlegroups.com. +subscribe is the key, which is appended to the end of group’s email address. (Group Name) is the name of the group. Space is substituted by “-” (hyphen).
> ```
> could you fix it ? thank you.

Yes.
see the new files.
I have fix it.

**Comment by fangjianmin** [comment]
rebuild the project

**Pull request merged**
