### PR TITLE
update quick-start-docker doc

### LINKED ISSUE #64: nacos-docker 文档错误
在快速开始 nacos-docker 单机模式示例中，没有 standalone.yaml 文件
```
docker-compose -f example/standalone.yaml up
```

### PR DESCRIPTION
**Pull request by liangyuanpeng**
## What is the purpose of the change

update doc for quick start 

fixes #64 

## Brief changelog

update doc for quick start 
add ``Common property configuration`` and ``Nacos + Grafana + Prometheus`` 
 update`` standalone up``

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/nacos-group/nacos-group.github.io/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [x] Format the pull request title like `Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Test your code locally by running `docsite start`, and make sure it works as expected.
- [x] Make sure no files under build directory is added.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

**Comment by liangyuanpeng** [comment]
It's my fault I didn't notice pr  [fix 64, 文档错误](#65) , but I think my pr is better,

**Comment by caojiele** [comment]
> It's my fault and I didn't notice pr : [fix 64, 文档错误](#65) , but I think my pr is better,

Hi, lack of relative should be html & json file, please submit the running locally success again.

**Comment by liangyuanpeng** [comment]
@caojiele done and thank you for your reply


```
How to Contribute
Create an issue first to description the issue
Do not use git add . to commit all the changes.
Just push your changed files, such as:
*.md
blog.js or docs.js or site.js
Send a PR to master branch.
```

i realy i just change xx.md and push *.md 
if need push html & json file, Maybe the README.md needs to be updated

**Comment by caojiele** [comment]
> @caojiele done and thank you for your reply
> 
> ```
> How to Contribute
> Create an issue first to description the issue
> Do not use git add . to commit all the changes.
> Just push your changed files, such as:
> *.md
> blog.js or docs.js or site.js
> Send a PR to master branch.
> ```
> 
> I realy i just change xx.md and push *.md
> If you need to push html & json file, maybe the README.md needs to be updated

Good advice! if travis ci is able to complete, this description is no problem.

**Pull request merged**
