### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by yaojingguo**
## What is the purpose of the change

Fix typo.

## Brief changelog

Fix some typos.

### CODE REVIEW

**Comment by caojiele** [comment]
Hi, need to compile, missing page files.

**Comment by yaojingguo** [comment]
Could please explain which page files are missed?  I have only updated some existing Markdown files.

**Comment by caojiele** [comment]
> Could please explain which page files are missed? I have only updated some existing Markdown files.

* open-api.html 
* open-api.json 
* deployment.html
* deployment.json

**Comment by yaojingguo** [comment]
I have tried to build the site and failed when runing `npm i`.
```
$ npm i
npm i
npm WARN deprecated core-js@1.2.7: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm WARN deprecated babel-eslint@6.1.2: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
npm WARN deprecated extract-text-webpack-plugin@2.1.2: Deprecated. Please use https://github.com/webpack-contrib/mini-css-extract-plugin
npm WARN deprecated babel-preset-es2015@6.22.0: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read https://babeljs.io/env to update!
npm WARN deprecated gulp-util@2.2.20: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm ERR! Linux 4.15.0-122-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "i"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /root/code/nacos-group.github.io/npm-debug.log
```

Can you please supply the missing files and take over this PR?

@caojiele

**Comment by caojiele** [comment]
> I have tried to build the site and failed when runing `npm i`.
> 
> ```
> $ npm i
> npm i
> npm WARN deprecated core-js@1.2.7: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
> npm WARN deprecated babel-eslint@6.1.2: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
> npm WARN deprecated extract-text-webpack-plugin@2.1.2: Deprecated. Please use https://github.com/webpack-contrib/mini-css-extract-plugin
> npm WARN deprecated babel-preset-es2015@6.22.0: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read https://babeljs.io/env to update!
> npm WARN deprecated gulp-util@2.2.20: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
> npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
> npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
> npm ERR! Linux 4.15.0-122-generic
> npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "i"
> npm ERR! node v8.10.0
> npm ERR! npm  v3.5.2
> npm ERR! code EMISSINGARG
> 
> npm ERR! typeerror Error: Missing required argument #1
> npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
> npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
> npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
> npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
> npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
> npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
> npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
> npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
> npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
> npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
> npm ERR! typeerror This is an error with npm itself. Please report this error at:
> npm ERR! typeerror     <http://github.com/npm/npm/issues>
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /root/code/nacos-group.github.io/npm-debug.log
> ```
> 
> Can you please supply the missing files and take over this PR?
> 
> @caojiele

Try upgrading node to V8.16.0.

**Pull request closed without merging**
