### PR TITLE
feat: add google and baidu search

### LINKED ISSUE #61: Hope user manual can search by keyword
Noticed Nacos website has no search button, it will be nice if support search by keyword.

### PR DESCRIPTION
**Pull request by caojiele**
## What is the purpose of the change

Fix #61 , add google and baidu search.

## Brief changelog

XXXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/nacos-group/nacos-group.github.io/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [x] Format the pull request title like `Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Test your code locally by running `docsite start`, and make sure it works as expected.
- [x] Make sure no files under build directory is added.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

**Comment by purple-force** [comment]
试着替换下更好的全局搜索方案algolia

**Comment by caojiele** [comment]
> 试着替换下更好的全局搜索方案algolia

14天免费使用？

**Comment by purple-force** [comment]
没这个限制吧

**Comment by caojiele** [comment]
> 没这个限制吧

WX20190724-164519@2x

**Comment by purple-force** [comment]
14天免费体验所有功能，之后服务降级而已

**Comment by caojiele** [comment]
> 14天免费体验所有功能，之后服务降级而已

先用这个吧，后续我再用algolia。

**Pull request merged**
