### PR TITLE
[Doc] Add Rainbond Nacos doc

### PR DESCRIPTION
**Pull request by dazuimao1990**
## What is the purpose of the change

Add Rainbond Nacos dosc

#262 

## Brief changelog

XXXXX

Follow this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [GITHUB_issue](https://github.com/nacos-group/nacos-group.github.io/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a GITHUB issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue.
- [ ] Format the pull request title like `Fix UnknownException when host config not exist #XXX`. Each commit in the pull request should have a meaningful subject line and body.
- [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [ ] Test your code locally by running `docsite start`, and make sure it works as expected.
- [ ] Make sure no files under build directory is added.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

### CODE REVIEW

**Review by KomachiSion — CHANGES_REQUESTED** [review]
I think the best path is in `blog/xxx`. 
And Can you optimize the article such as add some background information or introduce in opening?

You can refer to https://nacos.io/zh-cn/blog/apisix.html 

What's more, can Rainbond supported Nacos 2.X first? The Nacos 1.X is too old.

**Comment by dazuimao1990** [comment]
Thank you for your advice.
Nacos2.x support is a good idea, I need some time to matching it.
I will complete the adaptation work and re-commit the document as soon as possible.
😊

**Comment by dazuimao1990** [comment]
> I think the best path is in `blog/xxx`. And Can you optimize the article such as add some background information or introduce in opening?
> 
> You can refer to https://nacos.io/zh-cn/blog/apisix.html
> 
> What's more, can Rainbond supported Nacos 2.X first? The Nacos 1.X is too old.

Hi I submitted an additional commit to PR, including:
- Change the path of the documents to blog/
- Rainbond has been adapted to Nacos 2.0.4

Please review it. 😊
Have a nice day~

**Review by KomachiSion — APPROVED** [review]

**Comment by KomachiSion** [comment]
Thanks for your blog, we will publish this doc to nacos.io after few days.

**Pull request merged**
